metadata:
  name: Inputs and outputs
inputs:
  input_a: 
    description: 'Input a'
    required: false
    default: '1'
  input_b: 
    description: 'Input b'
    required: false
    default: '1'
jobs:
  inputs-job:
    runs-on: ['linux']
    steps:
      - run: echo "hello ${{ inputs.input_a }}"
      - run: echo "hello ${{ inputs.input_b }}"
  output-job:
    runs-on: ['linux']
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
    - id: step1
      run: echo "::set-output name=test::hello"
    - id: step2
      run: echo "::set-output name=test::world"
  thisIsAFailure:
        runs-on: ['robotframework']
        steps:
        -  uses: actions/checkout@v2
           with:
              repository: https://github.com/SquashTF-workshop/robotTFParamCheck
        -  uses: robotframework/robot@v1
           with:
               datasource: robotTFParamCheck/robot_community.robot
  thisIsASuccess:
    runs-on: junit
    steps:
    - uses: actions/checkout@v2
      with:
        repository: https://github.com/SquashTF-workshop/junitCalc
    - uses: junit/execute@v1
      with:
        test: junitCalc/squash.tfauto.CalculatorTest#addSuccess
outputs:
  workflow_output1:
    description: "The first job output"
    value: ${{ jobs.output-job.outputs.output1 }}
  workflow_output2:
    description: "The second first job output"
    value: ${{ jobs.output-job.outputs.output2 }}
